version: '3.3'

services:
    mysql:
        image: mysql:5.7
        restart: always
        container_name: mysql
        environment: 
            MYSQL_DATABASE: cinema
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports: 
            - 3306:3306
        volumes: 
            - data:/var/lib/mysql
        networks:
            - dbnet
    adminer:
        image: dockette/adminer
        restart: always
        ports:
            - 8000:80
        networks:
            - dbnet
    postgres:
        image: postgres
        volumes:
        - ./postgres/data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password
    keycloak:
        image: quay.io/keycloak/keycloak:latest
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: postgres
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_SCHEMA: public
            DB_PASSWORD: password
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: password
        ports:
            - 8080:8080
        depends_on:
            - postgres
networks: 
    dbnet:

volumes: 
    data:
