spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/cinema?useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    